# fonts/menu-builder.toml
module = "icon"

[glyphs]
edit = "fontawesome-pencil"
save = "fontawesome-floppy"
trash = "linecons-trash"
search = "fontawesome-search"
cancel = "fontawesome-cancel"
settings = "fontawesome-cog"
home = "fontawesome-home"
new = "fontawesome-plus"
copy = "fontawesome-clone"